apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 String: postgres =  cG9zdGdyZXM=
  # Base64 String: EsteEsUnPasswordSecreto =  RXN0ZUVzVW5QYXNzd29yZFNlY3JldG8=
  # echo -n postgres | base4 (Para crear el texto en base64)
  DB_USER: cG9zdGdyZXM= 
  DB_PASSWORD: RXN0ZUVzVW5QYXNzd29yZFNlY3JldG8=